import ChatUI from "@/components/ChatUI";

export default function CuidadoChat() {
  return (
    <main className="min-h-screen bg-cuidado-gradient text-cuidado-white p-4">
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="text-center space-y-2">
          <h1 className="text-2xl font-semibold font-display">CUIDADO Assistant</h1>
          <p className="text-sm opacity-70">
            This is the reference assistant interface used inside Pagi Hall.  
            Responses are generated by your local model via Ollama.
          </p>
        </div>
        
        <ChatUI />
        
        <div className="text-center text-xs opacity-60 space-y-1">
          <p>Powered by CUIDADO Engine — Careful Intelligence for Human Systems</p>
          <p>Visit <a href="/cuidado" className="text-cuidado-bronze hover:text-cuidado-teal transition-colors">the engine page</a> to learn more</p>
        </div>
      </div>
    </main>
  );
}
